### PR TITLE
Completely rearchitect how this library works

### LINKED ISSUE #1: Design thoughts
I think the current `AbstractAuthenticator` implementation may be trying to fulfill too many concerns, at least for a default implementation. Currently, it:

1. extracts a token from a request;
2. maintains accessors for the token;
3. maintains accessors for the error code and message;
4. maintains accessors for permissions.

The way in which 1 is done may vary depending on the authentication scheme in use, so I think it makes sense to leave this responsibility with the authenticator.

I'm not sure 2 is necessary, at least not for our use case. We should be able to have Auryn fetch the token instance from the authenticator once per request -- and that should happen on each request -- and return the same instance for subsequent reads.

3 can be handled outside the authenticator. One approach to that would be returning a response object that includes either the token or error information with appropriately semantic accessors. Another would be to either have a token object returned or throw a normalized exception or set of exceptions for failures.

4 seems like unclean separation of concerns as well, because it's combining authentication (identifying the user) and authorization (based on authentication, what operations the user has access to). If this remains, we may want to consider moving authorization-related functionality to a separate interface that each authenticator can implement or not depending on availability of support and need for that functionality.

I'd like to see us have an `AuthenticatorInterface` interface that defines a minimal implementation. Given my comments above, I think that is limited to concern 1 above. Here's one possible implementation:

```php
// src/AuthenticatorInterface.php
interface AuthenticatorInterface
{
    /**
     * @param \Psr\Http\Message\RequestInterface $request
     * @return \Spark\Auth\Token
     */
    public function authenticate(RequestInterface $request);
}

// src/Token.php
class Token
{
    /**
     * @var string
     */
    protected $token;

    /**
     * @var array
     */
    protected $metadata;

    /**
     * @param string $token
     * @param array $metadata
     */
    public function __construct($token, array $metadata)
    {
         $this->token = $token;
         $this->metadata = $metadata;
    }

    /**
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * @param string|null $key
     * @return mixed
     */
    public function getMetadata($key = null)
    {
        if ($key !== null) {
             return isset($this->metadata[$key]) ? $this->metadata[$key] : null;
        }
        return $this->metadata;
    }
}
```

### PR DESCRIPTION
**Pull request by elazar**
And fix a few small things discovered in the process.

Fixes #1.

**DO NOT MERGE THIS YET**. It will break [api-auth-jwt](https://github.com/wheniwork/api-auth-jwt) and by proxy [reporting-api](https://github.com/wheniwork/reporting-api) if merged right now. The current purpose of the PR is to make sure this implementation is sufficient to the satisfaction of the team. If so, other PRs will be opened in these repos to make related changesets to accommodate this one.

**Changes**
* Add [examples](https://github.com/sparkphp/auth/tree/feature/refactor#authentication-handler) to README -- review these for an overview of how these changes work
* Remove [`AbstractAuthenticator`](https://github.com/sparkphp/auth/blob/master/src/AbstractAuthenticator.php), because it involves too many concerns -- see #1 for related discussion
* Remove [`AbstractPermission`](https://github.com/sparkphp/auth/blob/master/src/AbstractPermissions.php) because it appears to be unused and relates to authorization rather than authentication
* Add the [`Token`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Token.php) and [`Credentials`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Credentials.php) value object classes to encapsulate authentication token metadata and user credentials respectively
* Add [`ExtractorInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Token/ExtractorInterface.php), [`HeaderExtractor`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Token/HeaderExtractor.php), and [`QueryExtractor`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Token/QueryExtractor.php) under the [`Token` subnamespace](https://github.com/sparkphp/auth/tree/feature/refactor/src/Token) for extracting authentication token strings from [`ServerRequestInterface`](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php) instances
* Add [`ExtractorInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Credentials/ExtractorInterface.php) and [`JsonExtractor`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Credentials/JsonExtractor.php) under the [`Credentials` subnamespace](https://github.com/sparkphp/auth/tree/feature/refactor/src/Credentials) for extracting user credentials from [`ServerRequestInterface`](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php) instances
* Add [`AdapterInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/AdapterInterface.php) to represent authentication adapters for validating authentication tokens and user credentials
* Add [`UnauthorizedException`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Exception/UnauthorizedException.php) for when authentication fails due to the request lacking an authentication token and user credentials
* Add [`RequestFilterInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/RequestFilterInterface.php) for determining whether authentication
  should be applied to a request
* Modify [`AuthHandler`](https://github.com/sparkphp/auth/blob/feature/refactor/src/AuthHandler.php) to use authentication adapter, token extractor, user credentials extractor, request filter, and [`UnauthorizedException`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Exception/UnauthorizedException.php) instances where appropriate
* Remove [`FakeAuthenticator`](https://github.com/sparkphp/auth/blob/master/tests/Fake/FakeAuthenticator.php) from test suite, because mocking of [`AdapterInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/AdapterInterface.php) in the [`AuthHandlerTest`](https://github.com/sparkphp/auth/blob/feature/refactor/tests/AuthHandlerTest.php) suite should cover the same use cases
* Add [`GeneratorInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Jwt/GeneratorInterface.php) and [`ParserInterface`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Jwt/ParserInterface.php) under the [`Jwt`](https://github.com/sparkphp/auth/tree/feature/refactor/src/Jwt) subnamespace with implementations for the firebase/php-jwt and lcobucci/jwt libraries and a [`Configuration`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Jwt/Configuration.php) value object class for common configuration settings.
* Modify the test suite to use Phake for mocking

**Fixes**
* Tweak Composer dependency versions to use the carot operator
* Make [`AuthHandler`](https://github.com/sparkphp/auth/blob/feature/refactor/src/AuthHandler.php) explicitly implement [`MiddlewareInterface`](https://github.com/sparkphp/adr/blob/master/src/MiddlewareInterface.php)
* Modify `getStatusCode()` return values for [`AuthException`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Exception/AuthException.php) and [`InvalidException`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Exception/InvalidException.php) to be appropriate for their use cases

/cc @dolfelt @shadowhand @ameech

### CODE REVIEW

File: src/AdapterInterface.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+     * Validates a set of user credentials.
+     *
+     * - If the user credentials are valid, a new authentication token is
+     *   created and a corresponding Token instance is returned.
+     * - If the user credentials are invalid, an InvalidException instance is
+     *   thrown.
+     * - If for some reason the user credentials cannot be validated, an
+     *   AuthException instance is thrown.
+     *
+     * @param \Spark\Auth\Credentials $credentials
```
Comment (shadowhand) [inline src/AdapterInterface.php]: Why a leading `\`?

File: src/AuthHandler.php [hunk 2]
```diff
@@ -1,28 +1,63 @@
...
+
 namespace Spark\Auth;
 
-use Psr\Http\Message\RequestInterface as Request;
 use Psr\Http\Message\ResponseInterface as Response;
-
-class AuthHandler
+use Psr\Http\Message\ServerRequestInterface as Request;
+use Spark\Adr\MiddlewareInterface;
+use Spark\Auth\AdapterInterface as Adapter;
```
Comment (shadowhand) [inline src/AuthHandler.php]: I can't say that I love these aliases. To me it feels like unnecessary obfuscation.

File: src/Credentials.php [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+{
+    /**
+     * @var string
+     */
+    private $username;
+
+    /**
+     * @var string
+     */
+    private $password;
```
Comment (shadowhand) [inline src/Credentials.php]: What if credentials is something other than a username and password?

File: src/Exception/UnauthorizedException.php [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+/**
+ * Exception that occurs when a user does not provide authentication
+ * credentials.
+ */
+class UnauthorizedException extends AuthException
+{
+    public function __construct($message = null, $code = 0, \Exception $previous = null)
+    {
+        if (!$message) {
+            $message = 'No authentication token was specified.';
```
Comment (shadowhand) [inline src/Exception/UnauthorizedException.php]: Couldn't this default be in the constructor signature?

File: src/Jwt/FirebaseGenerator.php [hunk 5]
```diff
@@ -0,0 +1,78 @@
+<?php
+namespace Spark\Auth\Jwt;
+
+use DateTime;
+use Firebase\JWT\JWT;
+use Psr\Http\Message\ServerRequestInterface as Request;
```
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: Why does it have to be `ServerRequestInterface`? Couldn't it be just `RequestInterface`?

File: src/Jwt/FirebaseParser.php [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+     * @param string $algorithm Optional algorithm, defaults to 'HS256'
+     */
+    public function __construct($key, $algorithm = 'HS256')
+    {
+        $this->key = $key;
+        $this->algorithm = $algorithm;
+    }
+
+    /**
+     * {@inheritDoc}
```
Comment (shadowhand) [inline src/Jwt/FirebaseParser.php]: This is the incorrect usage of `@inheritdoc`. It should not be wrapped in `{ ... }` when used this way.

File: src/Jwt/FirebaseGenerator.php [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+     * @param string $key Key used to sign the token
+     * @param integer $ttl Time-to-live for the token, in seconds
+     * @param string $algorithm Optional algorithm, defaults to 'HS256'
+     */
+    public function __construct(
+        Request $request,
+        DateTime $now,
+        $key,
+        $ttl,
+        $algorithm = 'HS256'
```
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: I'm not entirely convinced that having these defaults in the constructor is correct.

File: src/Token/ExtractorInterface.php [hunk 8]
```diff
@@ -0,0 +1,17 @@
+<?php
+namespace Spark\Auth\Token;
+
+use Psr\Http\Message\ServerRequestInterface as Request;
```
Comment (shadowhand) [inline src/Token/ExtractorInterface.php]: Again, why does it have to be server  request?

File: src/Token/HeaderExtractor.php [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+    /**
+     * {@inheritDoc}
+     */
+    public function getToken(Request $request)
+    {
+        $token = $request->getHeaderLine($this->header);
+        if (empty($token)) {
+            return null;
+        }
+        return $token;
```
Comment (shadowhand) [inline src/Token/HeaderExtractor.php]:
```php
return $token ?: null;
```

?

File: src/AdapterInterface.php (hunk 1 above)
Comment (elazar) [inline src/AdapterInterface.php]: To indicate that it's relative to the global namespace, as opposed to being a subnamespace of the one specified in the `namespace` directive of this file.

File: src/AuthHandler.php (hunk 2 above)
Comment (elazar) [inline src/AuthHandler.php]: We can remove them. My purpose in using them was admittedly mostly brevity, as the `Interface` postfix doesn't add anything in context with respect to the function of each class instance.

File: src/Credentials.php (hunk 3 above)
Comment (elazar) [inline src/Credentials.php]: Can you give an example use case?

File: src/Exception/UnauthorizedException.php (hunk 4 above)
Comment (elazar) [inline src/Exception/UnauthorizedException.php]: I believe the issue is signature compatibility with the parent class implementation, i.e. it wouldn't be `E_STRICT` compliant.

File: src/Jwt/FirebaseGenerator.php (hunk 5 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: In the context of this specific class, it could, yes. I can change that. In some other classes in this PR, such as those under the `Token` and `Credentials` subnamespaces, they depend on methods specific to `ServerRequestInterface`.

File: src/Jwt/FirebaseGenerator.php (hunk 7 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: Open to suggestions of how else to incorporate them. This seemed easiest with respect to how to configure the injector to generate the object. Save for `$algorithm`, because it has a default, and maybe `$ttl` because we could have a sane default for it, all the others parameters are logically required.

File: src/Token/ExtractorInterface.php (hunk 8 above)
Comment (elazar) [inline src/Token/ExtractorInterface.php]: Look at the implementations in this case: they use methods like `getHeaderLine()` and `getQueryParams()`, which are specific to `ServerRequestInterface`.

File: src/Jwt/FirebaseParser.php (hunk 6 above)
Comment (elazar) [inline src/Jwt/FirebaseParser.php]: Thanks. Fixed all instances of this. Apparently you have to scroll a bit in the [related documentation](http://phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag) to read the warning that indicates I was doing this incorrectly.

File: src/Token/HeaderExtractor.php (hunk 9 above)
Comment (elazar) [inline src/Token/HeaderExtractor.php]: Fixed.

File: src/AdapterInterface.php [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+     *   instance is thrown.
+     *
+     * @param string $token
+     * @return \Spark\Auth\Token
+     * @throws \Spark\Auth\Exception\InvalidException if an invalid auth token
+     *         is specified
+     * @throws \Spark\Auth\Exception\AuthException if another error occurs
+     *         during authentication
+     */
+    public function validateToken($token);
```
Comment (dolfelt) [inline src/AdapterInterface.php]: Should this pass in `\Spark\Auth\Token` to mirror the method below?

File: src/AuthHandler.php [hunk 11]
```diff
@@ -1,28 +1,63 @@
...
-
-        // Throw an error if the token is invalid.
-        // Doesn't throw an error if the token is not set.
-        $this->authenticator->ensureValid();
+        if ($token = $this->token->getToken($request)) {
+            $this->adapter->validateToken($token);
+        } elseif ($credentials = $this->credentials->getCredentials($request)) {
+            $this->adapter->validateCredentials($credentials);
+        } else {
+            throw new UnauthorizedException;
```
Comment (dolfelt) [inline src/AuthHandler.php]: How would we handle requests that we want to have be unauthenticated?

File: src/AuthHandler.php [hunk 12]
```diff
@@ -1,28 +1,63 @@
...
+    protected $adapter;
+
+    /**
+     * @param \Spark\Auth\Token\ExtractorInterface $token
+     * @param \Spark\Auth\Credentials\ExtractorInterface $credentials
+     * @param \Spark\Auth\Adapter\AdapterInterface $adapter
+     */
+    public function __construct(
+        TokenExtractor $token,
+        CredentialsExtractor $credentials,
```
Comment (dolfelt) [inline src/AuthHandler.php]: I still feel like there should be a way to merge these two into one `ExtractorInterface` so we don't have to include both of them here.

**Comment by dolfelt** [comment]
Love the enhanced readme file! :+1:

File: src/AdapterInterface.php (hunk 10 above)
Comment (elazar) [inline src/AdapterInterface.php]: It presently doesn't, though I suppose it could. That would involve shifting the responsibility for decoding / parsing the token to the extractor versus the adapter, and I suppose we're kinda sorta already doing that for credentials, e.g. in [`JsonExtractor`](https://github.com/sparkphp/auth/blob/feature/refactor/src/Credentials/JsonExtractor.php).

File: src/AuthHandler.php (hunk 12 above)
Comment (elazar) [inline src/AuthHandler.php]: As I said in chat, they really are two different concerns / use cases: either the user is submitting credentials to get a token or they're making a subsequent request with a token that needs to be validated.

I don't see any present / likely use cases wherein we'd be extracting a token or credentials from the request in the exact same way, so it seems counterintuitive to conflate them.

File: src/AuthHandler.php (hunk 11 above)
Comment (elazar) [inline src/AuthHandler.php]: We could add support for a whitelist based on request method and URI that's passed into the constructor as an array.

File: src/AdapterInterface.php (hunk 10 above)
Comment (elazar) [inline src/AdapterInterface.php]: Hm... looking at this further, I think the reason I didn't take this approach when I came up with the design is that it couples the logic for extracting the token string with the logic of parsing / decoding the token, which makes the code less reusable in other contexts.

For example, a JWT token and an HMAC token could both be included in a request header, and if we couple handling of these two concerns, we end up duplicating the logic to extract the token string in both implementations.

File: src/AuthHandler.php (hunk 2 above)
Comment (elazar) [inline src/AuthHandler.php]: Fixed.

File: README.md [hunk 13]
```diff
@@ -1,14 +1,219 @@
...
-[![Latest Stable Version](https://img.shields.io/packagist/v/sparkphp/Auth.svg)](https://packagist.org/packages/sparkphp/Auth)
+[![Latest Stable Version](https://img.shields.io/packagist/v/sparkphp/auth.svg)](https://packagist.org/packages/sparkphp/auth)
 [![Code Quality](https://img.shields.io/codeclimate/github/sparkphp/Auth.svg)](https://codeclimate.com/github/sparkphp/Auth)
 
-A simple middleware for creating custom authentication for your APIs. Attempts to be [PSR-1](http://www.php-fig.org/psr/psr-1/),
-[PSR-2](http://www.php-fig.org/psr/psr-2/), [PSR-4](http://www.php-fig.org/psr/psr-4/) and
-[PSR-7](http://www.php-fig.org/psr/psr-7/) compliant. Works great in applications that use the [ADR](https://github.com/pmjones/adr)
-pattern.
+A simple middleware for creating custom authentication for your APIs. Attempts to be [PSR-1](http://www.php-fig.org/psr/psr-1/), [PSR-2](http://www.php-fig.org/psr/psr-2/), [PSR-4](http://www.php-fig.org/psr/psr-4/) and [PSR-7](http://www.php-fig.org/psr/psr-7/) compliant. Works great in applications that use the [ADR](https://github.com/pmjones/adr) pattern.
```
Comment (shadowhand) [inline README.md]: These couple of changes could be done on master.

File: README.md [hunk 14]
```diff
@@ -1,14 +1,219 @@
...
+
+### Authentication Handler
+
+[`AuthHandler`](https://github.com/sparkphp/auth/blob/master/src/AuthHandler.php) is a middleware component that coordinates authentication. It can be added to a [Spark](http://sparkphp.github.io/) [`Application`](https://github.com/sparkphp/spark/blob/master/src/Application.php) instance like so:
+
+```php
+$injector = new \Auryn\Injector;
```
Comment (shadowhand) [inline README.md]: I see inconsistency when it comes to having the leading `\` namespace separator. I personally prefer to always not have it, but we should probably choose one.

File: phpunit.php [hunk 15]
```diff
@@ -1,12 +1,9 @@
 <?php
 error_reporting(E_ALL);
-if (!defined('APP_PATH')) {
-    define('APP_PATH', __DIR__ . DIRECTORY_SEPARATOR);
-}
```
Comment (shadowhand) [inline phpunit.php]: Master branch change?

File: src/AuthHandler.php (hunk 12 above)
Comment (shadowhand) [inline src/AuthHandler.php]: Maybe it would simplify the entire design of this of there were separate middlewares for credentials and tokens?

```
class TokenAuthHandler implements MiddlewareInterface
{
    public function __construct(
        ExtractorInterface $extractor,
        AdapterInterface $adapter
    ) { ... }
}
```

Maybe they could share a `AuthMiddlewareInterface`?

File: src/AuthHandler.php [hunk 16]
```diff
@@ -1,28 +1,66 @@
...
-        // Doesn't throw an error if the token is not set.
-        $this->authenticator->ensureValid();
+    /**
+     * @param \Psr\Http\Message\ServerRequestInterface $request
+     * @param \Psr\Http\Message\ResponseInterface $response
+     * @param callable $next
+     * @return array
+     */
+    public function __invoke(
+        ServerRequestInterface $request,
```
Comment (shadowhand) [inline src/AuthHandler.php]: Would it work to set an attribute `requires_auth` on the request by the routing handler?

File: src/AuthHandler.php (hunk 11 above)
Comment (shadowhand) [inline src/AuthHandler.php]: Would it work to set an attribute `requires_auth` on the request by the routing handler?

File: src/Credentials.php (hunk 3 above)
Comment (shadowhand) [inline src/Credentials.php]: For instance, and email and a password (not much different, but different naming). Or a [X.509](https://en.wikipedia.org/wiki/X.509)?

File: src/Credentials.php [hunk 17]
```diff
@@ -0,0 +1,41 @@
+<?php
+namespace Spark\Auth;
+
+class Credentials
+{
+    /**
+     * @var string
+     */
+    private $username;
```
Comment (shadowhand) [inline src/Credentials.php]: Perhaps this just needs to be less specific, and be `$identifier`?

File: src/Credentials/JsonExtractor.php [hunk 18]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    /**
+     * @inheritDoc
+     */
+    public function getCredentials(ServerRequestInterface $request)
+    {
+        $json = json_decode($request->getBody()->getContents(), true);
+
+        if (!is_array($json)) {
```
Comment (shadowhand) [inline src/Credentials/JsonExtractor.php]: You don't actually need this condition, the `empty` statements below make it redundant.

File: src/Exception/InvalidException.php [hunk 19]
```diff
@@ -13,6 +21,6 @@ public function __construct($message = null, $code = 0, \Exception $previous = n
 
     public function getStatusCode()
     {
-        return 400;
+        return 403;
```
Comment (shadowhand) [inline src/Exception/InvalidException.php]: This [doesn't match HTTP spec][1] and should be `401`. But that isn't perfect and there isn't a perfect option because of the RFC restrictions on HTTP 401 status. The non-standard HTTP statuses 498 or 499 could be used. [Github does use HTTP 401][2] so maybe we should just take the practical route instead of being pedantic?

[1]: http://stackoverflow.com/a/6937030/49146
[2]: https://developer.github.com/v3/#authentication

Comment (shadowhand) [inline src/Exception/InvalidException.php]: Or... I'm a moron and misread the class name. I'll leave my comment up for cross link references.

File: composer.json [hunk 20]
```diff
@@ -5,12 +5,15 @@
...
-        "psr/http-message": "^1.0"
+        "psr/http-message": "^1",
+        "sparkphp/adr": "^0.2"
     },
     "require-dev": {
-        "phpunit/phpunit": "~4.6",
-        "satooshi/php-coveralls": "0.6.1",
-        "zendframework/zend-diactoros": "~1.0"
+        "firebase/php-jwt": "^3",
+        "lcobucci/jwt": "^3",
```
Comment (shadowhand) [inline composer.json]: Shouldn't we also `suggest` these JWT packages?

File: src/Credentials/ExtractorInterface.php [hunk 21]
```diff
@@ -0,0 +1,19 @@
...
+interface ExtractorInterface
+{
+    /**
+     * Attempts to extract user credentials from a request.
+     *
+     * - If user credentials are present, a corresponding Credentials instance
+     *   is returned.
+     * - If no credentials are present, null is returned.
+     *
+     * @param \Psr\Http\Message\ServerRequestInterface $request
```
Comment (shadowhand) [inline src/Credentials/ExtractorInterface.php]: You have a `use` statement, so you don't actually need to hint the full class name.

File: src/Jwt/FirebaseGenerator.php [hunk 22]
```diff
@@ -0,0 +1,78 @@
...
+     * @param string $key Key used to sign the token
+     * @param integer $ttl Time-to-live for the token, in seconds
+     * @param string $algorithm Optional algorithm, defaults to 'HS256'
+     */
+    public function __construct(
+        RequestInterface $request,
+        DateTime $now,
+        $key,
+        $ttl,
+        $algorithm = 'HS256'
```
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: This signature still irks me. I don't have a good solution though, other than adding another value object (`GeneratorConfig`?) instead of the raw values.

File: src/Jwt/LcobucciParser.php [hunk 23]
```diff
@@ -0,0 +1,40 @@
...
+use Spark\Auth\Token;
+
+/**
+ * Parser for JWT authentication token strings that uses the lcobucci/jwt
+ * library.
+ */
+class LcobucciParser implements ParserInterface
+{
+    /**
+     * @var \Lcobucci\JWT\Parser $parser
```
Comment (shadowhand) [inline src/Jwt/LcobucciParser.php]: Same, you don't need to have a FQCN for something that is imported with `use`.

File: src/Token.php [hunk 24]
```diff
@@ -0,0 +1,45 @@
...
+    public function getToken()
+    {
+        return $this->token;
+    }
+
+    /**
+     * @param string|null $key
+     * @return mixed
+     */
+    public function getMetadata($key = null)
```
Comment (shadowhand) [inline src/Token.php]: Is it worthwhile to have `$key = null, $default = null`?

File: src/Token/HeaderExtractor.php [hunk 25]
```diff
@@ -0,0 +1,32 @@
...
+        $this->header = (string) $header;
+    }
+
+    /**
+     * @inheritDoc
+     */
+    public function getToken(ServerRequestInterface $request)
+    {
+        $token = $request->getHeaderLine($this->header);
+        return $token ?: null;
```
Comment (shadowhand) [inline src/Token/HeaderExtractor.php]: And now you could have:

```php
return $request->getHeaderLine($this->header) ?: null;
``` 

:sunglasses:

Comment (shadowhand) [inline src/Token/HeaderExtractor.php]: The default for `getHeaderLine` is an empty string... does it really matter if it is `null`?

Comment (shadowhand) [inline src/Token/HeaderExtractor.php]: Also, `getHeaderLine` will return a concatenated string of all the header values matching the name... is that really what we want? Or would it be better to have:

```php
$tokens = $request->getHeader($this->header);
return $tokens ? current($tokens) : null;
```

File: README.md (hunk 13 above)
Comment (elazar) [inline README.md]: Yeah, they can. I'll move them over.

File: README.md (hunk 14 above)
Comment (elazar) [inline README.md]: I agree that it should be consistent. I'm admittedly partial to including it because it removes any potential for ambiguity in absolute versus relative namespace references.

File: composer.json (hunk 20 above)
Comment (elazar) [inline composer.json]: Good point. Added.

File: phpunit.php (hunk 15 above)
Comment (elazar) [inline phpunit.php]: Moved.

File: src/AuthHandler.php (hunk 12 above)
Comment (elazar) [inline src/AuthHandler.php]: Assuming we did this, how would we know if authentication was successful? Having these consolidated into a single middleware allows us to check for both conditions and then throw an exception if neither is met. Is there a use case for which we wouldn't want to check for both a token and user credentials?

File: src/AuthHandler.php (hunk 11 above)
Comment (elazar) [inline src/AuthHandler.php]: Think that may be addressing the concern in the wrong place. If we hypothetically had an API that was completely public, it would make more sense to simply not add `AuthHandler` to the application's middleware at all and have that be all that's required versus also requiring configuration in `RouteHandler`.

File: src/Credentials.php (hunk 17 above)
Comment (elazar) [inline src/Credentials.php]: Done.

File: src/Credentials.php (hunk 3 above)
Comment (elazar) [inline src/Credentials.php]: Fair enough. Changed `$username` to `$identifier`. Do we need an equivalent renaming of `$password`?

File: src/Credentials/ExtractorInterface.php (hunk 21 above)
Comment (elazar) [inline src/Credentials/ExtractorInterface.php]: Fixed.

File: src/Credentials/JsonExtractor.php (hunk 18 above)
Comment (elazar) [inline src/Credentials/JsonExtractor.php]: Fixed.

File: src/Exception/InvalidException.php (hunk 19 above)
Comment (elazar) [inline src/Exception/InvalidException.php]: Yeah, 401 implies no credentials were provided, 403 implies credentials were provided and rejected. The latter use case is what this class is intended to address.

File: src/Exception/UnauthorizedException.php (hunk 4 above)
Comment (elazar) [inline src/Exception/UnauthorizedException.php]: Actually, in double-checking this, it looks like I was mistaken. Fixed.

File: src/Jwt/FirebaseGenerator.php (hunk 22 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: Using a value object here isn't a bad idea. It could include the key, TTL, and timestamp, since those appear to be common across both implementations. I think algorithm would have to remain separate because it's represented as a string in one implementation and a separate class instance in the other. Should I go ahead and make this change?

File: src/Jwt/LcobucciParser.php (hunk 23 above)
Comment (elazar) [inline src/Jwt/LcobucciParser.php]: Fixed in all classes under the `Jwt` subnamespace.

File: src/Token.php (hunk 24 above)
Comment (elazar) [inline src/Token.php]: Good question, not sure. I'd tend to think that data associated with the token will be specific to the user / account / etc. Not sure what meaningful default we'd use aside from `null`.

File: src/Token/HeaderExtractor.php (hunk 25 above)
Comment (elazar) [inline src/Token/HeaderExtractor.php]: Close, but not quite: it doesn't cover the edge case where the expected header is present, but empty. `getHeader()` is guaranteed to return an array, so I modified it to this, which should cover both cases (i.e. header is not present or is but is empty):

```php
$token = current($request->getHeader($this->header));
return $token ?: null;
```

File: src/AdapterInterface.php (hunk 1 above)
Comment (shadowhand) [inline src/AdapterInterface.php]: But we're not using them in our `use` statements, which makes it feel inconsistent.

File: src/AuthHandler.php (hunk 11 above)
Comment (shadowhand) [inline src/AuthHandler.php]: Actually pretty much every API is both public and private, because things like OPTIONS should require no auth.

File: src/Credentials.php (hunk 3 above)
Comment (shadowhand) [inline src/Credentials.php]: Perhaps, though I am less concerned about that.

File: src/Credentials/JsonExtractor.php [hunk 26]
```diff
@@ -0,0 +1,45 @@
...
+
+/**
+ * Extracts credentials from top-level properties of a JSON request body.
+ */
+class JsonExtractor implements ExtractorInterface
+{
+    /**
+     * @var string
+     */
+    protected $username;
```
Comment (shadowhand) [inline src/Credentials/JsonExtractor.php]: Should be this identifier?

File: src/Exception/AuthException.php [hunk 27]
```diff
@@ -1,18 +1,21 @@
...
+        $code = 0,
+        \Exception $previous = null
+    ) {
         parent::__construct($message, $code, $previous);
     }
 
     public function getStatusCode()
     {
-        return 401;
+        return 500;
```
Comment (shadowhand) [inline src/Exception/AuthException.php]: Why `500`? It's not really a server error if the user provided bad credentials.

File: src/Exception/InvalidException.php [hunk 28]
```diff
@@ -1,18 +1,26 @@
...
-    {
-        if (!$message) {
-            $message = 'The token being used is invalid.';
-        }
+    const CODE_TOKEN_EXPIRED = 1;
+    const CODE_TOKEN_INVALID = 2;
+    const CODE_CREDENTIALS_INVALID = 3;
+
+    public function __construct(
+        $message = 'The token being used is invalid.',
```
Comment (shadowhand) [inline src/Exception/InvalidException.php]: Exception messages should not contain a period, because a fully formatted trace would look like:

> The token being used is invalid. in SomeFile.php on line 123

Default PHP exceptions never include them for this reason.

File: src/Jwt/FirebaseGenerator.php (hunk 22 above)
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: I would like to see a value object be used. There should be a clear distinction between classes that collaborate and value objects. Any class that collaborates should take objects as its constructors. Value objects should take scalar values as options.

Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: Note to self: this is probably worth writing a blog post about.

File: tests/AuthHandlerTest.php [hunk 29]
```diff
@@ -1,32 +1,184 @@
...
+    public function dataProviderExceptions()
+    {
+        return [
+            [new InvalidException],
+            [new AuthException],
+        ];
+    }
+
+    /**
+     * @param \Spark\Auth\Exception\AuthException $exception
```
Comment (shadowhand) [inline tests/AuthHandlerTest.php]: Doesn't need the FQCN.

File: tests/AuthHandlerTest.php [hunk 30]
```diff
@@ -1,32 +1,184 @@
...
+
+        $response = $this->handler->__invoke($this->request, $this->response, [$this, 'next']);
+
+        $this->assertTrue($this->next_called);
+        $this->assertSame($this->response, $response);
+        Phake::verify($this->adapter)->validateCredentials($credentials);
+    }
+
+    /**
+     * @param \Spark\Auth\Exception\AuthException $exception
```
Comment (shadowhand) [inline tests/AuthHandlerTest.php]: Doesn't need the FQCN.

File: tests/Credentials/JsonExtractorTest.php [hunk 31]
```diff
@@ -0,0 +1,98 @@
...
+use PHPUnit_Framework_TestCase as TestCase;
+use Psr\Http\Message\ServerRequestInterface;
+use Psr\Http\Message\StreamInterface;
+use Spark\Auth\Credentials;
+use Spark\Auth\Credentials\JsonExtractor;
+
+class JsonExtractorTest extends TestCase
+{
+    /**
+     * @var \Spark\Auth\Credentials\JsonExtractor
```
Comment (shadowhand) [inline tests/Credentials/JsonExtractorTest.php]: ...

File: src/AdapterInterface.php (hunk 1 above)
Comment (elazar) [inline src/AdapterInterface.php]: I disagree.

Excluding them from `use` statements is more of a language convention than anything; they're always assumed to be relative to the global namespace by the PHP interpreter.

PHPDocumentor, which I'm assuming is a nontrivial part of the reason we're including docblocks to begin with, limits the [Type](http://phpdoc.org/docs/latest/references/phpdoc/types.html) portion of a [`@param` tag](http://phpdoc.org/docs/latest/references/phpdoc/tags/param.html) to either a FQCN or a class name relative to the namespace of the containing file, where the leading slash is [used to differentiate between the two](https://github.com/phpDocumentor/TypeResolver/blob/83e31258fb03b9a27884a83b81501cb4cb297a81/src/TypeResolver.php#L173-L195). As such, if we exclude it where FQCNs are used, the namespace portions are will be misinterpreted as being relative rather than absolute.

File: src/AuthHandler.php (hunk 11 above)
Comment (elazar) [inline src/AuthHandler.php]: Alternatively, we could do something like this:

```php
// src/RequestFilterInterface.php
use Psr\Http\Message\RequestInterface;
interface RequestFilterInterface
{
    /**
     * @return boolean
     */
    public function __invoke(RequestInterface $request);
}

// src/AuthHandler.php
// ...
class AuthHandler implements MiddlewareInterface
{
    /**
     * @var RequestFilterInterface
     */
    private $filter;
    public function __construct(
        // ...
        RequestFilterInterface $filter = null
    ) {
        // ...
        $this->filter = $filter;
    }
    public function __invoke(
        ServerRequestInterface $request,
        ResponseInterface $response,
        callable $next
    ) {
        if ($this->filter && call_user_func($this->filter, $request)) {
            // ...
        }
        return $next($request, $response);
    }
}
```

File: src/Credentials/JsonExtractor.php (hunk 26 above)
Comment (elazar) [inline src/Credentials/JsonExtractor.php]: Yup. Think I've got all instances fixed now.

File: src/Exception/AuthException.php (hunk 27 above)
Comment (elazar) [inline src/Exception/AuthException.php]: This exception isn't used for that use case: it's only thrown by adapters in cases where some error other than the user providing invalid or no credentials caused authentication to fail. `InvalidException` handles invalid credentials with a `403` status code, `UnauthorizedException` handles no credentials with a `401`.

File: src/Exception/InvalidException.php (hunk 28 above)
Comment (elazar) [inline src/Exception/InvalidException.php]: That's how it was when I got here. ;) But, fixed.

File: tests/AuthHandlerTest.php (hunk 29 above)
Comment (elazar) [inline tests/AuthHandlerTest.php]: Fixed.

File: tests/AuthHandlerTest.php (hunk 30 above)
Comment (elazar) [inline tests/AuthHandlerTest.php]: Fixed.

File: tests/Credentials/JsonExtractorTest.php (hunk 31 above)
Comment (elazar) [inline tests/Credentials/JsonExtractorTest.php]: Fixed.

File: src/AdapterInterface.php (hunk 1 above)
Comment (shadowhand) [inline src/AdapterInterface.php]: Hmm, TIL. Funny how we all use PHPdoc syntax but when was the last time you actually generated docs?

Comment (elazar) [inline src/AdapterInterface.php]: Point, though I suspect that's a habit that should be cultivated as we expand. No particular reason we can't include generating docs in our build process so far as I know.

File: src/AuthHandler.php (hunk 11 above)
Comment (shadowhand) [inline src/AuthHandler.php]: I like that.

File: src/Token.php (hunk 24 above)
Comment (shadowhand) [inline src/Token.php]: Nah, skip it.

**Comment by elazar** [comment]
@shadowhand Added JWT configuration value object and request filter support. Details in the `README`.

File: src/AuthHandler.php [hunk 32]
```diff
@@ -1,28 +1,76 @@
...
+     * @param ResponseInterface $response
+     * @param callable $next
+     * @return array
+     */
+    public function __invoke(
+        ServerRequestInterface $request,
+        ResponseInterface $response,
+        callable $next
+    ) {
+        if (!$this->filter || call_user_func($this->filter, $request)) {
```
Comment (shadowhand) [inline src/AuthHandler.php]: :+1:

File: src/Jwt/Configuration.php [hunk 33]
```diff
@@ -0,0 +1,58 @@
...
+     * @var DateTime
+     */
+    private $timestamp;
+
+    /**
+     * @param string $key Key used to sign the token
+     * @param integer $ttl Time-to-live for the token, in seconds
+     * @param DateTime $timestamp Timestamp used for token issuance and expiration
+     */
+    public function __construct($key, $ttl, DateTime $timestamp)
```
Comment (shadowhand) [inline src/Jwt/Configuration.php]: Wouldn't it be easier to define this as a `int $timestamp`?

File: src/Jwt/Configuration.php [hunk 34]
```diff
@@ -0,0 +1,58 @@
...
+    {
+        return $this->ttl;
+    }
+
+    /**
+     * @return DateTime
+     */
+    public function getTimestamp()
+    {
+        return clone $this->timestamp;
```
Comment (shadowhand) [inline src/Jwt/Configuration.php]: And then:

```php
return (new DateTime)->setTimestamp($this->timestamp);
```

?

File: src/Jwt/FirebaseGenerator.php [hunk 35]
```diff
@@ -0,0 +1,63 @@
...
+
+    /**
+     * @param RequestInterface $request
+     * @param Configuration $config
+     * @param string $algorithm Optional algorithm, defaults to 'HS256'
+     */
+    public function __construct(
+        RequestInterface $request,
+        Configuration $config,
+        $algorithm = 'HS256'
```
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: Why isn't this contained in the `Configuration`?

File: src/Jwt/FirebaseGenerator.php [hunk 36]
```diff
@@ -0,0 +1,63 @@
...
+    }
+
+    /**
+     * @param string $subject
+     * @return string
+     */
+    public function getToken($subject)
+    {
+        $issuer = (string) $this->request->getUri();
+        $issued_at = $this->config->getTimestamp()->format('U');
```
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: Especially since the `iat` is going to be timestamp anyways... why even bother with DateTime objects at all?

File: src/Jwt/FirebaseParser.php [hunk 37]
```diff
@@ -0,0 +1,54 @@
...
+    /**
+     * @var string
+     */
+    protected $algorithm;
+
+    /**
+     * @param Configuration $config
+     * @param string $algorithm Optional algorithm, defaults to 'HS256'
+     */
+    public function __construct($config, $algorithm = 'HS256')
```
Comment (shadowhand) [inline src/Jwt/FirebaseParser.php]: Type hint `$config`?

File: src/Jwt/Configuration.php (hunk 34 above)
Comment (elazar) [inline src/Jwt/Configuration.php]: We end up instantiating the object directly there, which makes testing difficult when we want to override the value. I'd rather inject whatever value we use.

File: src/Jwt/Configuration.php (hunk 33 above)
Comment (elazar) [inline src/Jwt/Configuration.php]: Maybe here, but it presents some other difficulties if we take that approach.

1. The value now has to be manually set in the Auryn Injector, where it can handle instantiating a `DateTime` object on its own.
2. We lose what validation `DateTime` offers of the value.

File: src/Jwt/FirebaseGenerator.php (hunk 35 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: Per our chat discussion, the algorithm is represented in different ways between different libraries. Firebase uses a string, Lcobucci uses a whole different class instance that the Auryn injector handles passing in. I'm only including in `Configuration` what's common across both implementations.

File: src/Jwt/FirebaseGenerator.php (hunk 36 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: See previous notes about validation and injection.

File: src/Jwt/Configuration.php (hunk 33 above)
Comment (shadowhand) [inline src/Jwt/Configuration.php]: But for injection, we can simply do:

```php
$injector->define(
    'Spark\\Auth\\Jwt\\Configuration',
    [
        ':key' => '...',
        ':ttl' => 3600, // in seconds, e.g. 1 hour,
        ':timestamp' => time(),
    ]
);
```

Which is effectively the same as what is happening right now.

File: src/Jwt/FirebaseParser.php (hunk 37 above)
Comment (elazar) [inline src/Jwt/FirebaseParser.php]: Fixed.

File: src/Jwt/FirebaseGenerator.php (hunk 35 above)
Comment (shadowhand) [inline src/Jwt/FirebaseGenerator.php]: As per chat, I think it would make sense to put the algorithm in the Configuration and figure out a way to do a factory inside of Lcobucci. There's [already precedent][1] for having a factory, and it would be fairly easy to build one that is [similar to this][2] that loads default classes unless overloaded.

[1]: https://github.com/lcobucci/jwt/blob/master/src/Claim/Factory.php
[2]: https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/GrantFactory.php

File: src/Jwt/Configuration.php (hunk 33 above)
Comment (elazar) [inline src/Jwt/Configuration.php]: Fine. Done.

File: src/Jwt/FirebaseGenerator.php (hunk 35 above)
Comment (elazar) [inline src/Jwt/FirebaseGenerator.php]: Done.

File: src/Jwt/LcobucciSignerFactory.php [hunk 38]
```diff
@@ -0,0 +1,35 @@
...
+    protected $map;
+    
+    public function __construct()
+    {
+        $ns = 'Lcobucci\\JWT\\Signer\\';
+        $this->map = [
+            'HS256' => $ns . 'Hmac\\Sha256',
+            'HS512' => $ns . 'Hmac\\Sha512',
+            'HS384' => $ns . 'Hmac\\Sha384',
+            'RS256' => $ns . 'Rsa\\Sha256',
```
Comment (shadowhand) [inline src/Jwt/LcobucciSignerFactory.php]: This works, but doesn't allow any kind of overloading. Are you going to finish it and submit a PR upstream?

Comment (elazar) [inline src/Jwt/LcobucciSignerFactory.php]: Added an `add()` method for overloading. Filed lcobucci/jwt#45 to gauge the likelihood of acceptance for an upstream contribution.

Comment (elazar) [inline src/Jwt/LcobucciSignerFactory.php]: @shadowhand Looks like it was done before in the 2.x branch of lcobucci/jwt and the maintainers subsequently didn't see a lot of value in it and removed it. If you want to argue for its inclusion, you've got a link to the upstream issue above. Otherwise, I think we can call this part finished.

**Comment by elazar** [comment]
@shadowhand seems satisfied with this as-is.

@dolfelt @ameech Speak now or forever hold your peace. :hear_no_evil:

**Comment by lcobucci** [comment]
@elazar and @shadowhand as I've spoke on lcobucci/jwt#47 I'll be suggest somethings here.

I'm really glad to see that you're using my library and I'll try to find a balance between the needs of both libraries.

File: src/Jwt/LcobucciSignerFactory.php (hunk 38 above)
Comment (lcobucci) [inline src/Jwt/LcobucciSignerFactory.php]: You can easily avoid this by configuring the signer FQCN in your configuration object (instead of the algorithm id). I know that it removes your standard across libraries, however the implementation details are very different and IMHO you shouldn't hide that from your users.

File: README.md [hunk 39]
```diff
@@ -5,10 +5,212 @@
...
+#### Lcobucci
+
+To use the [lcobucci/jwt](https://packagist.org/packages/lcobucci/jwt) library:
+
+```
+composer require "lcobucci/jwt:^3"
+```
+
+```php
+$injector->define(
```
Comment (lcobucci) [inline README.md]: It's important to remember that if you're using an asymmetric (which is recommended) you'll have a private and a public key.

File: src/Jwt/LcobucciParser.php [hunk 40]
```diff
@@ -0,0 +1,40 @@
...
+    {
+        $this->parser = $parser;
+    }
+
+    /**
+     * @inheritDoc
+     */
+    public function parseToken($token)
+    {
+        $parsed = $this->parser->parse((string) $token);
```
Comment (lcobucci) [inline src/Jwt/LcobucciParser.php]: I think that you forgot to:

1. Capture the parsing exception that would be thrown if the token is invalid (```\InvalidArgumentException``` for now);
1. Verify if the token signature is valid: ```if (!$parsed->verify($signer, $publicKey)) { /* Raise an exception because signature is not valid */ }```
1. Validate the token claims: ```if (!$parsed->validate($validationSet)) { /* Raise an exception because the token is expired or cannot yet be used or has any other invalid claim */ }```

File: README.md (hunk 39 above)
Comment (elazar) [inline README.md]: @lcobucci Sorry, when you say "an asymmetric," I'm not sure what you mean?

File: src/Jwt/LcobucciParser.php (hunk 40 above)
Comment (elazar) [inline src/Jwt/LcobucciParser.php]: Thanks, will add appropriate handling for these.

Side note: `\InvalidArgumentException` seems an odd one to use for this use case, seeing as I think it was intended to be used in lieu of scalar type hints:

> Exception thrown if an argument is not of the expected type.
> ~ http://php.net/manual/en/class.invalidargumentexception.php

Comment (lcobucci) [inline src/Jwt/LcobucciParser.php]: Indeed, I'll add a ParsingException or something for v4.

File: README.md (hunk 39 above)
Comment (lcobucci) [inline README.md]: Sorry, [asymmetric key](http://searchsecurity.techtarget.com/definition/asymmetric-cryptography).

RSA and ECDSA algorithms are way better and safer than HMAC.

Comment (elazar) [inline README.md]: Ah, gotcha. Will bear that in mind, thanks.

**Comment by elazar** [comment]
@shadowhand Made changes, mostly to `LcobucciParser` and `Configuration`, to implement suggestions made by @lcobucci.

File: src/AuthHandler.php (hunk 32 above)
Comment (shadowhand) [inline src/AuthHandler.php]: Actually instead of having this, it might be cleaner to do:

```php
if ($this->shouldFilter($request)) { ... }
```

Along with:

```php
private function shouldFilter(ServerRequestInterface $request)
{
    if (!$this->filter) {
        return true;
    }
    return call_user_func($this->filter, $request);
}
```

Not a significant change, but I think it makes the intent a lot more clear.

File: src/Jwt/Configuration.php [hunk 41]
```diff
@@ -0,0 +1,86 @@
...
+     * @param string $publicKey Public key used to sign the token
+     * @param integer $ttl Time-to-live for the token, in seconds
+     * @param string $algorithm
+     * @param integer $timestamp UNIX timestamp used for token issuance and expiration
+     * @param string $privateKey Private key used to sign the token
+     */
+    public function __construct($publicKey, $ttl, $algorithm, $timestamp = null, $privateKey = null)
+    {
+        $this->publicKey = $publicKey;
+        $this->ttl = $ttl;
```
Comment (shadowhand) [inline src/Jwt/Configuration.php]: Should be cast to integer, right?

File: src/Jwt/LcobucciSignerFactory.php [hunk 42]
```diff
@@ -0,0 +1,47 @@
...
+     * Map of algorithm identifiers to corresponding FQCNs for Signer classes
+     *
+     * @var array
+     */
+    protected $map;
+    
+    public function __construct()
+    {
+        $ns = 'Lcobucci\\JWT\\Signer\\';
+        $this->map = [
```
Comment (shadowhand) [inline src/Jwt/LcobucciSignerFactory.php]: I still don't like this because it doesn't allow the user to specify any new algos.

File: src/AuthHandler.php (hunk 32 above)
Comment (elazar) [inline src/AuthHandler.php]: Done.

File: src/Jwt/Configuration.php (hunk 41 above)
Comment (elazar) [inline src/Jwt/Configuration.php]: Yup, done.

File: src/Jwt/LcobucciSignerFactory.php (hunk 42 above)
Comment (elazar) [inline src/Jwt/LcobucciSignerFactory.php]: How so? See the `add()` method in this class.

File: src/Jwt/LcobucciParser.php [hunk 43]
```diff
@@ -0,0 +1,128 @@
...
+
+    /**
+     * @param Parser $parser
+     * @param LcobucciSignerFactory $factory
+     * @param Configuration $config
+     * @param ValidationData $validation
+     */
+    public function __construct(
+        Parser $parser,
+        LcobucciSignerFactory $factory,
```
Comment (shadowhand) [inline src/Jwt/LcobucciParser.php]: The more I think about this, the more I think this should be replaced by a `Signer` instance. The configuration value still matters, because we can do:

```php
if ($this->config->getAlgorithm() !== $this->signer->getAlgoritmId()) {
    throw new \RuntimeException('nope');
}
```

Relevant to the topic at hand...

doesnotfit

File: src/Jwt/LcobucciSignerFactory.php (hunk 42 above)
Comment (shadowhand) [inline src/Jwt/LcobucciSignerFactory.php]: :ok:

File: src/Jwt/LcobucciParser.php (hunk 43 above)
Comment (elazar) [inline src/Jwt/LcobucciParser.php]: I thought part of the point of the recent changes was to keep DRY by only requiring the algorithm to be specified in one place? At this point, we seem to backpedaling toward my original approach, where the algorithm wasn't part of the common configuration, the Firebase constructor took an algorithm string, and Lcobucci constructor took a `Signer` instance.

Comment (shadowhand) [inline src/Jwt/LcobucciParser.php]: The factory made a lot of sense in my head until I actually worked out the functionality... :neutral_face:

Comment (lcobucci) [inline src/Jwt/LcobucciParser.php]: I still think that using the Signer FQCN will makes things simpler. I believe that you're thinking to add another JWT implementations and if you take a look at namshi/jose and Spomky-Labs/jose you'll see that there's no "standard". So I believe that letting users choose theirs stuff would be probably better.

File: src/Jwt/Configuration.php [hunk 44]
```diff
@@ -0,0 +1,86 @@
...
+    private $privateKey;
+
+    /**
+     * @param string $publicKey Public key used to sign the token
+     * @param integer $ttl Time-to-live for the token, in seconds
+     * @param string $algorithm
+     * @param integer $timestamp UNIX timestamp used for token issuance and expiration
+     * @param string $privateKey Private key used to sign the token
+     */
+    public function __construct($publicKey, $ttl, $algorithm, $timestamp = null, $privateKey = null)
```
Comment (lcobucci) [inline src/Jwt/Configuration.php]: An important thing to remember: when using asymmetric keys you **sign** with the private key and **verify** the signature with the public key :smile:

**Comment by elazar** [comment]
@shadowhand Removed the signer factory per our earlier discussion.

File: README.md [hunk 45]
```diff
@@ -5,10 +5,215 @@
...
+composer require "firebase/php-jwt:^3"
+```
+
+```php
+$injector->define(
+    'Spark\\Auth\\Jwt\\Configuration',
+    [
+        ':key' => '...',
+        ':ttl' => 3600, // in seconds, e.g. 1 hour
+        ':algorithm' => 'HS256',
```
Comment (shadowhand) [inline README.md]: :+1:

**Comment by shadowhand** [comment]
Looks good to me! Squash it and merge when ready.

**Comment by elazar** [comment]
Squashed. Working on PRs for api-data-layer, api-auth-jwt, and reporting-api. Will try to merge them all at once with appropriate tags and Composer version requirements.

File: src/AdapterInterface.php (hunk 1 above)
Comment (ameech) [inline src/AdapterInterface.php]: PHPdoc is pretty dang handy in PHPStorm.
